[build]
  base = "."
  command = "npm install && npm run build"
  functions = "netlify/functions"
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18.16.0"

[dev]
  port = 5000
  targetPort = 5000
  autoLaunch = true 